### ISSUE TITLE
always requires a : in PRIVMSG?

### ISSUE THREAD

**Issue by TurBoss** [Yaribz/SpringIrcBridge#3]
Hi I'm deplying the lounge a web client for the irc

the version 1.5.0 works well but the master branch of the lounge does not send all messages to the server
they toldme tha could be the irc bridge that allways require ":" in PRIVMSG???????

i'm not sure about this just asking here

thx

here is the issue I opened in thelounge 
https://github.com/thelounge/lounge/issues/383

**Comment by Yaribz** [comment]
They are right, it's a bug in the bridge, I will fix that.

PRIVMSG always has exactly 2 parameters and the second parameter (message text) often contains spaces, so most IRC clients choose the simplest way to encode these commands which is to always prefix the second parameter with `:` (to allow spaces in message text). This way it works in all cases, and the IRC clients don't have to check if the message contains spaces. That's why this bug hasn't been detected yet.

**Comment by TurBoss** [comment]
thank you
